### ISSUE TITLE
Error: Cannot find module '@angular-devkit/core'

### ISSUE THREAD

**Issue by sudhircodefire** [coreui/coreui-free-angular-admin-template#58]
Node -v = v8.9.4
npm -v = 4.3.0

Error:
module.js:540
    throw err;
    ^

Error: Cannot find module '@angular-devkit/core'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\wamp\www\ngApi\node_modules\@angular-devkit\schematics\src\tree\virtual.js:10:16)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)

**Comment by Boboss74** [comment]
solution here #54

**Comment by jogaian282** [comment]
Install npm i @angular-devkit/core --save-dev as development dependency and try

**Comment by xidedix** [comment]
I'm closing this since it appears to be inactive or answered above. Please comment and/or reopen if you feel the issue has not been resolved.
