### ISSUE TITLE
ERROR in ./node_modules/css-loader?

### ISSUE THREAD

**Issue by julianoctvaz** [coreui/coreui-free-angular-admin-template#62]
ERROR in ./node_modules/css-loader?{"sourceMap":false,"import":false}!./node_modules/postcss-loader/lib?{"ident":"postcss","sourceMap":false}!./node_modules/sass-loader/lib/loader.js?{"sourceMap":false,"precision":8,"includePaths":[]}!./src/scss/style.scss
Module build failed: Error: ENOENT: no such file or directory, scandir '/Users/a/Desktop/Angular/CoreUI-Angular-master/Angular5_CLI_Full_Project/node_modules/node-sass/vendor'
    at Object.fs.readdirSync (fs.js:904:18)
    at Object.getInstalledBinaries (/Users/a/Desktop/Angular/CoreUI-Angular-master/Angular5_CLI_Full_Project/node_modules/node-sass/lib/extensions.js:128:13)
    at foundBinariesList (/Users/a/Desktop/Angular/CoreUI-Angular-master/Angular5_CLI_Full_Project/node_modules/node-sass/lib/errors.js:20:15)
    at foundBinaries (/Users/a/Desktop/Angular/CoreUI-Angular-master/Angular5_CLI_Full_Project/node_modules/node-sass/lib/errors.js:15:5)
    at Object.module.exports.missingBinary (/Users/viitra/Desktop/Angular/CoreUI-Angular-master/Angular5_CLI_Full_Project/node_modules/node-sass/lib/errors.js:45:5)
    at module.exports (/Users/a/Desktop/Angular/CoreUI-Angular-master/Angular5_CLI_Full_Project/node_modules/node-sass/lib/binding.js:15:30)
    at Object.<anonymous> (/Users/a/Desktop/Angular/CoreUI-Angular-master/Angular5_CLI_Full_Project/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/a/Desktop/Angular/CoreUI-Angular-master/Angular5_CLI_Full_Project/node_modules/sass-loader/lib/loader.js:3:14)
    at Module._compile (module.js:635:30)
 @ ./src/scss/style.scss 4:14-199
 @ multi ./node_modules/flag-icon-css/css/flag-icon.css ./node_modules/font-awesome/css/font-awesome.css ./node_modules/simple-line-icons/css/simple-line-icons.css ./src/scss/style.scss

**Comment by jctvEC** [comment]
Actually, i updated all this modules in the error, and runned..

**Comment by joelgtsantos** [comment]
I could solved this by reinstall node-sass

`npm i node-sass --s`
