### ISSUE TITLE
Startup error with @angular/cli@6.0.1

### ISSUE THREAD

**Issue by phcollignon** [coreui/coreui-free-angular-admin-template#82]
How to reproduce 
`
npm install -g @angular/cli  (6.0.1 is latest now by default)
git clone https://github.com/coreui/coreui-free-bootstrap-admin-template.git my-project
cd my-project
npm install
ng serve
`
You get this error at startup
`
Local workspace file ('angular.json') could not be found.
Error: Local workspace file ('angular.json') could not be found.
    at WorkspaceLoader._getProjectWorkspaceFilePath (/home/phico/.nvm/versions/node/v8.10.0/lib/node_modules/@angular/cli/models/workspace-loader.js:37:19)
    at WorkspaceLoader.loadWorkspace (/home/phico/.nvm/versions/node/v8.10.0/lib/node_modules/@angular/cli/models/workspace-loader.js:24:21)
    at ServeCommand._loadWorkspaceAndArchitect (/home/phico/.nvm/versions/node/v8.10.0/lib/node_modules/@angular/cli/models/architect-command.js:180:32)
    at ServeCommand.<anonymous> (/home/phico/.nvm/versions/node/v8.10.0/lib/node_modules/@angular/cli/models/architect-command.js:47:25)
    at Generator.next (<anonymous>)
    at /home/phico/.nvm/versions/node/v8.10.0/lib/node_modules/@angular/cli/models/architect-command.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/home/phico/.nvm/versions/node/v8.10.0/lib/node_modules/@angular/cli/models/architect-command.js:3:12)
    at ServeCommand.initialize (/home/phico/.nvm/versions/node/v8.10.0/lib/node_modules/@angular/cli/models/architect-command.js:46:16)
    at Object.<anonymous> (/home/phico/.nvm/versions/node/v8.10.0/lib/node_modules/@angular/cli/models/command-runner.js:87:23)
`

I try to update .. with ng update .. but no way

**Comment by BizyDev** [comment]
You're probably not running `npm install` command from your project folder.

**Comment by phcollignon** [comment]
Sorry I opened issue to fast .. angular.json was missing due to my-project wrong copy ..
